### ISSUE TITLE
cl-lib 0.5 is obsolete by gnu

### ISSUE THREAD

**Issue by jinn8522** [xuchunyang/osx-dictionary.el#11] opened 2016-07-01 08:54 UTC
when I update the packages by melpa, I found the osx-dictionary don't work. I found the cl-lib 0.5 is obsolete,replaced by version 1.0 and I can't install the older version. I want to know If anyway I can fix this.
my emacs version is 24.5.1,and the osx-dictionary.el verion is 20160628.111.best wishes and thanks for your help.

**Comment by xuchunyang** [comment] 2016-07-01 09:08
cl-lib 1.0 is already included with Emacs in 24.5 so you don't need to install cl-lib 0.5. cl-lib 0.5 from gnu elpa is for older Emacs versions that don't have cl-lib.

> when I update the packages by melpa, I found the osx-dictionary don't work

You need to describe the problem. simply "don't work" doesn't help.

**Comment by jinn8522** [comment] 2016-07-01 09:36
the dictionary window is blank ,after press 'o'  key, the dictionary app opened with the definition of word 'nil'

**Comment by xuchunyang** [comment] 2016-07-02 14:40
It works well here. I'm going to close this issue since I don't
know how to reproduce. If the issue still concerns you, please
open a new issue with detailed description on the issue itself
and steps to reproduce it (i.e., the **facts**), it is not required to
mention your posit explanations.

**Closed by xuchunyang** 2016-07-02 14:40 UTC

**Comment by dsdshcym** [comment] 2016-09-18 07:46
I ran into the same problem here:

1. the dictionary window is blank
2. after press 'o', the dictionary app opened but it searches 'nil'
3. run `osx-dictionary-cli` will get a segmentation fault, even after recompilation

**Comment by dsdshcym** [comment] 2016-09-18 07:51
Here is the segmentation fault log:

[crash_log.txt](https://github.com/xuchunyang/osx-dictionary.el/files/478580/crash_log.txt)

**Comment by jinn8522** [comment] 2016-09-18 09:24
I sloved this problem by select another dictionary in apple's dictionary app.I hope this will give you some help.

发自我的 iPhone

**Comment by dsdshcym** [comment] 2016-09-18 09:29
@jinn8522 Thanks!

I set osx-dictionary-dictionary-choice to "English". And the problem is gone.

But I remember that when I used Emacs 24.5 and Xcode 7, I didn't have this problem.

Maybe you can take a look? @xuchunyang

(Or, if it's because my dictionary settings changed?)

**Comment by xuchunyang** [comment] 2016-09-18 10:58
@dsdshcym I have not encountered (or know the way to reproduce) the problem you described. I am using Emacs 25.1 and Xcode 7.3. However, if `osx-dictionary-cli` doesn't work under certain conditions (for example, on your system), I am not very surprised. The code of `osx-dictionary.m` is indeed not very reliable, it uses some private APIs.
